import { CardTS } from "./../interface/interface";
export const Card: CardTS[] = [
  {
    count: 1,
    title: "Iphone 10",
    name: "iphone",
    id: "1",
    desription:
      "Технические характеристики Apple iPhone 11. SoC Apple A13 Bionic (6 ядер: 2 высокопроизводительных + 4 энергоэффективных) + система Neural Engine третьего поколения. Сопроцессор движения Apple M13,",
    img: "https://i.ebayimg.com/00/s/NjQwWDY0MA==/z/z3gAAOSw7RRhC~GO/$_57.JPG?set_id=8800005007",
    bool: false,
    price: 100,
    year: 2029,
    sale: 45,
    color: "red",
    coment: [],
  },
  {
    count: 1,
    id: "2",
    title: "iphone 11",
    name: "iphone",
    desription:
      "Технические характеристики Apple iPhone 11. SoC Apple A13 Bionic (6 ядер: 2 высокопроизводительных + 4 энергоэффективных) + система Neural Engine третьего поколения. Сопроцессор движения Apple M13,",
    img: "https://iplus.com.ge/images/thumbnails/4889/4000/detailed/1/WWRU_iPhone12_Q121_Blue_PDP-Image-1A.jpg",
    bool: false,
    price: 200,
    year: 2043,
    color: "red",
    sale: 90,
    coment: [],
  },
  {
    count: 1,
    id: "3",
    title: "Iphone 12",
    name: "iphone",
    desription:
      "Технические характеристики Apple iPhone 11. SoC Apple A13 Bionic (6 ядер: 2 высокопроизводительных + 4 энергоэффективных) + система Neural Engine третьего поколения. Сопроцессор движения Apple M13,",
    img: "https://assets.swappie.com/swappie-product-iphone-12-pro-max-pacific-blue.png",
    bool: false,
    price: 300,
    year: 2021,
    sale: 79,
    color: "green",
    coment: [],
  },
  {
    count: 1,
    id: "4",
    title: "Sumsung A",
    name: "sumsung",
    desription:
      "Технические характеристики Apple iPhone 11. SoC Apple A13 Bionic (6 ядер: 2 высокопроизводительных + 4 энергоэффективных) + система Neural Engine третьего поколения. Сопроцессор движения Apple M13,",
    img: "https://5zv.by/image/cache/data/products/Samsung/samsung_a30_3-1000x1000.jpg",
    bool: false,
    price: 400,
    year: 2022,
    color: "blue",
    sale: 32,
    coment: [],
  },
  {
    count: 1,
    id: "5",
    title: "Sumsung A12",
    name: "sumsung",
    desription:
      "Технические характеристики Apple iPhone 11. SoC Apple A13 Bionic (6 ядер: 2 высокопроизводительных + 4 энергоэффективных) + система Neural Engine третьего поколения. Сопроцессор движения Apple M13,",
    img: "https://st41.stpulscen.ru/images/product/359/115/748_big.jpg",
    bool: false,
    price: 500,
    year: 2021,
    color: "green",
    sale: 80,
    coment: [],
  },
  {
    count: 1,
    id: "6",
    title: "Sumsung A10",
    name: "sumsung",
    desription:
      "Технические характеристики Apple iPhone 11. SoC Apple A13 Bionic (6 ядер: 2 высокопроизводительных + 4 энергоэффективных) + система Neural Engine третьего поколения. Сопроцессор движения Apple M13,",
    img: "https://d28i4xct2kl5lp.cloudfront.net/product_images/1516126578.25.jpg",
    bool: false,
    price: 24,
    year: 2018,
    color: "red",
    sale: 3,
    coment: [],
  },
  {
    count: 1,
    id: "7",
    title: "Nokia",
    name: "nokia",
    desription:
      "Финская транснациональная компания, производитель телекоммуникационного оборудования для мобильных, фиксированных, широкополосных и IP-сетей. В 2000-е годы доминировала на мировом рынке мобильных телефонов.",
    img: "https://i.ebayimg.com/images/g/Jf8AAOSw1BlZUpTf/s-l640.jpg",
    bool: false,
    price: 304,
    year: 2017,
    sale: 10,
    coment: [],
    color: "red",
  },
  {
    count: 1,
    id: "8",
    title: "Nokia A10",
    name: "nokia",
    desription:
      "Финская транснациональная компания, производитель телекоммуникационного оборудования для мобильных, фиксированных, широкополосных и IP-сетей. В 2000-е годы доминировала на мировом рынке мобильных телефонов.",
    img: "https://www.360fiyat.com/wp-content/uploads/2021/03/Nokia-2.2-4-2048x2048.jpg",
    bool: false,
    price: 299,

    color: "red",
    year: 2009,
    coment: [],
    sale: 30,
  },
  {
    count: 1,
    id: "9",
    title: "Nokia A89",
    name: "nokia",
    desription:
      "Финская транснациональная компания, производитель телекоммуникационного оборудования для мобильных, фиксированных, широкополосных и IP-сетей. В 2000-е годы доминировала на мировом рынке мобильных телефонов.",
    img: "https://images.zakupka.com/i3/firms/27/77/77854/nokia-3310-novyy-korpus-vvostanovlenyy_17a7075e2af3204_800x600.jpg",
    bool: false,
    price: 299,
    year: 2019,
    coment: [],
    color: "blue",
    sale: 20,
  },
];

export const IMGS_SLIDER: Array<string> = [
  "https://postila.ru/data/64/e5/26/7b/64e5267b1dd463c6203fd5f5e29af6c0b6989ddd8b03a4ecba90f78365944350.jpg",
  "https://fotorelax.ru/wp-content/uploads/2016/02/Pictures-of-butterflies-16.jpg",
  "https://proprikol.ru/wp-content/uploads/2019/12/krasivye-kartinki-pro-zimu-2.jpg",
  "https://i.ucrazy.ru/files/i/2010.11.9/1289239709_70.jpg",
];
